// Generated by scaffold_replica.js from spec.pages (owner: scaffold). On every route or store change it renders the
// active page's view into its [data-view] section, empties and hides the others (so data-testids never repeat),
// then calls shell.update(ctx). shell.mount(ctx) runs once at start. ctx = { route, store, data, router }.
import * as data from '__DATA__';
import { store } from './store.js';
import { router } from './router.js';
import * as shell from './shell.js';
__IMPORTS__

const VIEWS = __VIEWS__;
const sections = [...document.querySelectorAll('[data-view]')];
const context = () => ({ route: router.current(), store, data, router });

// One broken view must not blank the shell or other owners' checks: rethrow later (the checker still reports it
// as an uncaught error) and carry on drawing.
function attempt(fn) {
  try { fn(); } catch (err) { queueMicrotask(() => { throw err; }); }
}

function draw() {
  const ctx = context();
  for (const el of sections) {
    const active = el.dataset.view === ctx.route.page;
    el.hidden = !active;
    if (active) attempt(() => VIEWS[ctx.route.page].render(el, ctx));
    else el.replaceChildren();
  }
  attempt(() => shell.update(ctx));
}

// A broken image becomes a neutral inline SVG so the layout holds (the checker still reports the original failure).
const FALLBACK = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(
  '<svg xmlns="http://www.w3.org/2000/svg" width="300" height="300" viewBox="0 0 300 300"><rect width="300" height="300" fill="#eeeeee"/>' +
  '<circle cx="115" cy="110" r="20" fill="#cccccc"/><path d="M70 220l55-70 40 45 30-35 45 60z" fill="#cccccc"/></svg>');
document.addEventListener('error', e => {
  const img = e.target;
  if (img.tagName === 'IMG' && img.src !== FALLBACK) {
    img.removeAttribute('srcset');
    img.src = FALLBACK;
    img.classList.add('img-fallback');
  }
}, true);

attempt(() => shell.mount(context()));
router.subscribe(draw);
store.subscribe(draw);
draw();
