// Hash router generated by scaffold_replica.js from spec.pages[].pattern (owner: scaffold).
// router.current() -> { page, view, params } (view === page === the page id). A pattern is a hash path with ":name"
// and optional ":name?" segments, or a list of such paths for one page; the query string (?k=...) is parsed into
// params; pages are tried in order and the first match wins; an unmatched hash goes to pages[0].
const PAGES = __PAGES__;

export const slug = s => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const segments = path => path.replace(/^#?\/?/, '').split('/').filter(Boolean);
const paramName = seg => (seg[0] === ':' ? seg.slice(1).replace(/\?$/, '') : null);
const decode = s => { try { return decodeURIComponent(s); } catch { return s; } };
function splitHash(hash) {
  const s = String(hash ?? '').replace(/^#/, '');
  const q = s.indexOf('?');
  return q < 0 ? [s, ''] : [s.slice(0, q), s.slice(q + 1)];
}

// ponytail: segments match by position, so an optional ":name?" only makes sense at the end of a pattern;
// give the page a list of patterns for anything fancier.
function matchPattern(pattern, parts) {
  const segs = segments(pattern);
  if (parts.length > segs.length) return null;
  const params = {};
  for (const [i, seg] of segs.entries()) {
    const name = paramName(seg);
    if (!name) {
      if (parts[i] !== seg) return null;
    } else if (i < parts.length) params[name] = decode(parts[i]);
    else if (!seg.endsWith('?')) return null;
  }
  return params;
}

// Pure, so it can be tested without a browser.
export function matchRoute(pages, hash) {
  const [path, query] = splitHash(hash);
  const parts = segments(path);
  const qs = Object.fromEntries(new URLSearchParams(query));
  for (const p of pages) {
    for (const pattern of [].concat(p.pattern)) {
      const params = matchPattern(pattern, parts);
      if (params) return { page: p.id, view: p.id, params: { ...qs, ...params } };
    }
  }
  return { page: pages[0].id, view: pages[0].id, params: qs };
}

// href('detail', { id: 'B0X' }) -> '#/dp/B0X'; params that aren't in the path go to the query string:
// href('search', { k: 'wireless headphones' }) -> '#/s?k=wireless+headphones'. Empty values are dropped.
export function href(pageId, params = {}, pages = PAGES) {
  const page = pages.find(p => p.id === pageId);
  if (!page) throw new Error(`href: unknown page "${pageId}"`);
  const given = Object.fromEntries(Object.entries(params).filter(([, v]) => v != null && v !== ''));
  const has = name => Object.hasOwn(given, name);
  // Of the patterns whose required params are all given, use the one that puts the most params in the path.
  let best = null;
  for (const pattern of [].concat(page.pattern)) {
    const segs = segments(pattern);
    if (segs.some(s => paramName(s) && !s.endsWith('?') && !has(paramName(s)))) continue;
    const used = segs.filter(s => paramName(s) && has(paramName(s))).length;
    if (!best || used > best.used) best = { segs, used };
  }
  if (!best) throw new Error(`href: page "${pageId}" needs params for ${[].concat(page.pattern).join(' or ')}`);
  const rest = { ...given };
  const path = [];
  for (const seg of best.segs) {
    const name = paramName(seg);
    if (!name) path.push(seg);
    else if (has(name)) {
      path.push(encodeURIComponent(rest[name]));
      delete rest[name];
    }
  }
  const qs = new URLSearchParams(rest).toString();
  return '#/' + path.join('/') + (qs ? '?' + qs : '');
}

const listeners = new Set();
let route = matchRoute(PAGES, location.hash);
let path = segments(splitHash(location.hash)[0]).join('/');
window.addEventListener('hashchange', () => {
  route = matchRoute(PAGES, location.hash);
  // A new path (page, id, page number) starts at the top; a query-only change (filters, sort) keeps the scroll.
  const next = segments(splitHash(location.hash)[0]).join('/');
  if (next !== path) window.scrollTo(0, 0);
  path = next;
  listeners.forEach(fn => fn(route));
});

export const router = {
  current: () => route,
  subscribe(fn) { listeners.add(fn); return () => listeners.delete(fn); },
  go(hash) { location.hash = hash; }
};
