// App state generated by scaffold_replica.js from spec.state, spec.locale, spec.currency and spec.currencyDigits (owner: scaffold).
// store.get() / store.set(patch | state => patch) / store.subscribe(fn). Only spec.state.persist keys are saved.
export const LOCALE = __LOCALE__;
export const CURRENCY = __CURRENCY__;
export const MONEY_OPTIONS = __MONEY_OPTIONS__; // shared by money() and ui.priceHtml(), so they never disagree
const INITIAL = __INITIAL__;
const PERSIST = __PERSIST__;
const KEY = __KEY__;

const kind = v => (Array.isArray(v) ? 'array' : v === null ? 'null' : typeof v);

function load(key) {
  try {
    const saved = JSON.parse(localStorage.getItem(key));
    return kind(saved) === 'object' ? saved : {};
  } catch {
    try { localStorage.removeItem(key); } catch { /* storage blocked */ }
    return {};
  }
}

export function createStore(initial, persist = [], key = KEY) {
  const saved = load(key);
  let state = { ...initial };
  // A saved value is used only when it has the initial value's type, so stale or hand-edited storage can't break views.
  for (const k of persist) {
    if (Object.hasOwn(saved, k) && (initial[k] == null || kind(saved[k]) === kind(initial[k]))) state[k] = saved[k];
  }
  const listeners = new Set();
  return {
    get: () => state,
    set(patch) {
      state = { ...state, ...(typeof patch === 'function' ? patch(state) : patch) };
      try {
        localStorage.setItem(key, JSON.stringify(Object.fromEntries(persist.map(k => [k, state[k]]))));
      } catch { /* private mode / quota: keep working in memory */ }
      listeners.forEach(fn => fn(state));
    },
    subscribe(fn) { listeners.add(fn); return () => listeners.delete(fn); }
  };
}

export const store = createStore(INITIAL, PERSIST);

// Cart-like lists of { id, qty }. Pure, each returns a new list: store.set(s => ({ cart: addItem(s.cart, id) })).
export const addItem = (list = [], id, qty = 1) =>
  list.some(l => l.id === id) ? list.map(l => (l.id === id ? { ...l, qty: l.qty + qty } : l)) : [...list, { id, qty }];
export const setItemQty = (list = [], id, qty) =>
  qty > 0 ? list.map(l => (l.id === id ? { ...l, qty } : l)) : removeItem(list, id);
export const removeItem = (list = [], id) => list.filter(l => l.id !== id);
export const countItems = (list = []) => list.reduce((n, l) => n + l.qty, 0);
export const sumItems = (list = [], priceOf) => list.reduce((sum, l) => sum + (Number(priceOf(l.id)) || 0) * l.qty, 0);

const fmt = new Intl.NumberFormat(LOCALE, MONEY_OPTIONS);
export const money = n => fmt.format(n);
