// Markup helpers generated by scaffold_replica.js (owner: scaffold). Each returns an HTML string.
import { money, LOCALE, MONEY_OPTIONS } from './store.js';

const ENTITIES = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
export const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ENTITIES[c]);

// Unique per call. SVG gradient ids need it: a repeated id whose first copy sits in a hidden section renders empty.
let seq = 0;
export const uid = (prefix = 'uid') => `${prefix}-${++seq}`;

// Split price <span class="price"><sym>$</sym><whole>39</whole><frac>99</frac></span> for superscript styling, plus a
// visually-hidden full string so screen readers read "$39.99" (the split parts are aria-hidden). innerText holds both
// ("$39.99\n$3999"), so text checks match with includes(). position: relative keeps that absolutely positioned
// .sr-only copy inside scroll containers.
const fmt = new Intl.NumberFormat(LOCALE, MONEY_OPTIONS);
export function priceHtml(n, { split = true } = {}) {
  const full = esc(money(n));
  if (!split) return `<span class="price">${full}</span>`;
  const parts = fmt.formatToParts(n);
  const text = types => parts.filter(p => types.includes(p.type)).map(p => p.value).join('');
  const span = (cls, s) => (s ? `<span class="${cls}" aria-hidden="true">${esc(s)}</span>` : '');
  const sym = span('sym', text(['currency']));
  const num = span('whole', text(['minusSign', 'integer', 'group'])) + span('frac', text(['fraction']));
  const symFirst = parts.findIndex(p => p.type === 'currency') < parts.findIndex(p => p.type === 'integer');
  return `<span class="price" style="position: relative"><span class="sr-only">${full}</span>${symFirst ? sym + num : num + sym}</span>`;
}

// Rating stars filled with --color-star (empty part --color-star-empty); fractional ratings fill part of a star.
const STAR = 'M12 2.5l2.9 6.1 6.6.8-4.9 4.6 1.3 6.6L12 17.4l-5.9 3.2 1.3-6.6-4.9-4.6 6.6-.8z';
export function starsHtml(rating, { max = 5 } = {}) {
  const r = Math.max(0, Math.min(max, Number(rating) || 0));
  const star = i => {
    const id = uid('star');
    const fill = Math.round(Math.max(0, Math.min(1, r - i)) * 100);
    return `<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true" focusable="false"><defs><linearGradient id="${id}">` +
      `<stop offset="${fill}%" style="stop-color: var(--color-star, #de7921)"/><stop offset="${fill}%" style="stop-color: var(--color-star-empty, transparent)"/>` +
      `</linearGradient></defs><path d="${STAR}" fill="url(#${id})" style="stroke: var(--color-star, #de7921)" stroke-width="1.2"/></svg>`;
  };
  return `<span class="stars" role="img" aria-label="${r} out of ${max} stars">${Array.from({ length: max }, (_, i) => star(i)).join('')}</span>`;
}
