#!/usr/bin/env node
/**
 * brief.js — everything one agent needs, in one ~10 KB printout, so it doesn't read spec.json (~30 KB),
 * capture.json (~65 KB+), the generated sources or the reference docs. Those dumps stay in an agent's context
 * for every later turn, and context × turns is where a build's tokens go. It also answers what Builders used
 * to grep for: the layout contract, the markup ui.js emits, a sample record and every page's route.
 *
 * Usage:
 *   node scripts/brief.js --dir <replica> --owner <owner>     builder:<name> | builder:shell | data
 * Reads <dir>/spec.json, <dir>/target/summary.json (falls back to capture.json) and <dir>/css/tokens.css.
 * ponytail: per-field cuts, not a total budget; books briefs are 3–10 KB, amazon's 4-page spec ~9.5–11.5 KB.
 */
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { parseArgs } from './lib.js';

// Capture files are optional input: a missing, empty or corrupt one reads as null and the brief falls back.
const readJson = f => { try { return JSON.parse(fs.readFileSync(f, 'utf-8')); } catch { return null; } };
const cut = (s, n) => (s && s.length > n ? s.slice(0, n - 1) + '…' : s || '');
const style = o => Object.entries(o || {}).filter(([k, v]) => v && !['text', 'box'].includes(k) && v !== 'rgba(0, 0, 0, 0)' && v !== 'normal' && v !== 'none' && v !== '0px' && !/^0px none/.test(v))
  .map(([k, v]) => `${k} ${v}`).join('; ');

// One line per step: "goto / → fill search-input 'x' → expectCount book-card =20"
function stepLine(s) {
  const [k, v] = Object.entries(s)[0];
  const extra = ['value', 'contains', 'eq', 'min', 'max'].filter(x => s[x] !== undefined && x !== k).map(x => (x === 'eq' ? `=${s.eq}` : x === 'min' ? `≥${s.min}` : x === 'max' ? `≤${s.max}` : JSON.stringify(s[x])));
  return [k, v === true ? '' : v, ...extra].filter(x => x !== '').join(' ');
}

// "target/screens/home-{desktop,tablet,mobile}.png" when the files follow that naming, else the full list.
function screens(s) {
  const vps = Object.keys(s), brace = `{${vps.join(',')}}`;
  const pat = s[vps[0]].replace(`-${vps[0]}.`, `-${brace}.`);
  return vps.every(v => pat.replace(brace, v) === s[v]) ? `target/${pat}` : Object.values(s).map(x => 'target/' + x).join(', ');
}

function digestPage(sum, cap, source) {
  const p = sum?.pages?.find(x => x.name === source);
  if (p) return { keyElements: p.keyElements, cardGroups: p.cardGroups, interactive: p.interactive, headings: p.headings, screens: p.screens, states: p.states, pageHeight: p.pageHeight };
  const c = cap?.pages?.find(x => x.name === source);
  return c ? { keyElements: c.keyElements, cardGroups: (c.cardGroups || []).slice(0, 2), screens: c.screens, states: c.states, pageHeight: c.pageHeight } : null;
}

const API = `Runtime API (generated by scaffold — use it, don't read or edit its source):
  view module   export function render(el, ctx)   ctx = { route: { page, params }, store, data, router }
                Re-render el fully each call; handlers by assignment (el.onclick = e => …closest('[data-action]')).
  shell.js      export function mount(ctx) once; export function update(ctx) after every render.
  ../store.js   store.get() / store.set(patch | s => patch) / store.subscribe(fn); addItem(list,id,qty=1),
                setItemQty(list,id,qty), removeItem(list,id), countItems(list), sumItems(list, id => price), money(n)
  ../ui.js      esc(s), uid(prefix), priceHtml(n, { split }), starsHtml(rating, { max })
  ../router.js  href(pageId, params) → '#/…', router.go(hash), router.current(), slug(s)
  css           var(--<group>-<name>) from tokens.css only (no raw hex); scope rules under [data-view="<page id>"].
  data          ctx.data.<export> — never hard-code records; the full set replaces the seed later, same shape.`;

// Fixed: builder:shell builds index.html to this shape and owns the frame (shell.md says the same), so views
// don't grep base.css or index.html while it is still being written.
const LAYOUT = `Layout contract (index.html):
  <header class="site-header">…</header>
  <main id="content"><section data-view="<page id>">…</section>…</main>
  <footer class="site-footer">…</footer>
  builder:shell styles the header, the footer AND the page frame (#content width, gutters, panel background/
  border/shadow) at all 3 viewports. Views style only inside their own section: no outer page max-width,
  side margins or page background of their own.`;
const ATOMS = `.btn, .btn-primary · .breadcrumb (<ul class="breadcrumb"><li><a href>…</a></li>…<li class="active">…</li></ul>) ·
  .alert + .alert-success / .alert-info / .alert-warning · .badge · input, select, textarea, label · .price, .stars`;

// The real output of the replica's js/ui.js, so views style its classes without reading it.
async function helperMarkup(dir) {
  try {
    // store.js guards localStorage; stubbing it only silences Node's "--localstorage-file" warning.
    Object.defineProperty(globalThis, 'localStorage', { value: undefined, configurable: true });
    const ui = await import(pathToFileURL(path.join(dir, 'js', 'ui.js')).href);
    const { LOCALE, MONEY_OPTIONS } = await import(pathToFileURL(path.join(dir, 'js', 'store.js')).href);
    const price = ui.priceHtml(1234.5);
    const dec = new Intl.NumberFormat(LOCALE, MONEY_OPTIONS).formatToParts(1.5).find(p => p.type === 'decimal')?.value;
    const stars = ui.starsHtml(3.5);
    const svgs = stars.match(/<svg[^>]*>/g) || [];
    return ['Helper markup (js/ui.js output; style these classes, don\'t read ui.js):',
      `  priceHtml(1234.5)                 ${price}`,
      price.includes('class="frac"') && dec ? `    (parts are aria-hidden; no decimal-separator span, add .frac::before { content: ${JSON.stringify(dec)} } if the target shows one)` : '    (parts are aria-hidden)',
      `  priceHtml(1234.5, { split: false }) ${ui.priceHtml(1234.5, { split: false })}`,
      `  starsHtml(3.5)                    ${stars.slice(0, stars.indexOf('<svg'))}${svgs.length} × ${svgs[0]}…</svg></span>` +
        `  (gradient fill: ${[...new Set(stars.match(/--[\w-]+/g))].join(' / ')})`,
      '  .sr-only      visually hidden (base.css)',
      '  .img-fallback app.js swaps a broken <img> src for a grey placeholder SVG and adds this class'].join('\n');
  } catch (err) {
    return `Helper markup: js/ui.js did not import (${err.message.split('\n')[0]}); run scaffold first.`;
  }
}

// Long strings and arrays shortened, so a sample record shows the shape, not the content.
const short = (k, v) => (typeof v === 'string' ? cut(v, 80) : Array.isArray(v) && v.length > 3 ? [...v.slice(0, 3), `…+${v.length - 3}`] : v);

export async function brief(dir, owner) {
  const specPath = path.join(dir, 'spec.json');
  if (!fs.existsSync(specPath)) throw new Error(`no spec.json in ${dir}`);
  const spec = JSON.parse(fs.readFileSync(specPath, 'utf-8'));
  const sum = readJson(path.join(dir, 'target', 'summary.json'));
  // capture.json (big) only when summary.json lacks a captured page; digestPage falls back per page.
  const cap = (spec.pages || []).every(p => !p.source || sum?.pages?.some(x => x.name === p.source)) ? null : readJson(path.join(dir, 'target', 'capture.json'));
  const files = Object.entries(spec.files || {}).filter(([, o]) => o === owner).map(([f]) => f);
  const isShell = owner === 'builder:shell';
  const pages = (spec.pages || []).filter(p => (isShell ? true : p.owner === owner));
  const features = (spec.features || []).filter(f => f.owner === owner);
  const captured = p => digestPage(sum, cap, p.source);
  // The shell owns no page: it matches its header/footer on, and visual-checks, the first captured page.
  const shellPage = isShell ? (spec.pages || []).find(captured) : null;
  if (owner !== 'data' && !files.length && !pages.length && !features.length) throw new Error(`--owner ${owner} owns nothing in spec.json`);
  const out = [`# Brief: ${owner}   (replica ${dir})`, `Brand ${spec.brand || '?'} · ${spec.locale || 'en-US'} · ${spec.currency || 'USD'}${spec.currencyDigits != null ? ` (${spec.currencyDigits} decimals)` : ''} · stack ${spec.stack || 'vanilla'}`];
  out.push('', `Your files (write ONLY these): ${files.join(', ') || '(none)'}`);

  if (owner !== 'data') {
    out.push('', `Pages${isShell ? ' (the shell wraps every page; match header/footer at all 3 viewports)' : ''}:`);
    for (const p of pages) {
      const d = digestPage(sum, cap, p.source);
      out.push(`- ${p.id}  route ${p.route} · pattern ${[].concat(p.pattern || '').join(', ')} · module ${p.module || ''}${p.visualMaxHeight ? ` · visualMaxHeight ${JSON.stringify(p.visualMaxHeight)}` : ''}`);
      if (d?.screens) out.push(`  screens: ${screens(d.screens)}${d.pageHeight ? ` (target height ${d.pageHeight}px)` : ''}`);
      if (d?.states?.length) out.push(`  states: ${d.states.map(s => `${s.trigger} → target/${s.screenshot}`).join('; ')}`);
      if (p === shellPage) out.push('  ← your visual-check page: match the header, page frame and footer on its screenshots');
      if (p.notes) out.push(`  notes: ${cut(p.notes, isShell ? 150 : 700)}`);
    }
    const others = (spec.pages || []).filter(p => !pages.includes(p));
    if (others.length) out.push(`Other pages (link with href(id, params)): ${others.map(p => `${p.id} ${[].concat(p.pattern || '').join(' | ')} (e.g. ${p.route})`).join(' · ')}`);
    out.push('', LAYOUT, isShell ? '  Shared atoms you provide in css/base.css (views use these class names without reading base.css):'
      : '  Shared atoms builder:shell provides in css/base.css (use them; no need to read base.css):', '  ' + ATOMS);
    out.push('', `Features (${features.length}) — every data-testid in these steps must exist exactly as named:`);
    const ids = new Set();
    for (const f of features) {
      out.push(`- [${f.priority || 'must'}] ${f.id} (${f.page || ''}): ${(f.steps || []).map(stepLine).join(' → ')}`);
      for (const s of f.steps || []) for (const k of ['click', 'hover', 'fill', 'select', 'expectVisible', 'expectHidden', 'expectText', 'expectCount'])
        if (typeof s[k] === 'string' && !s[k].startsWith('css=')) ids.add(s[k]);
    }
    if (ids.size) out.push(`data-testids: ${[...ids].join(', ')}`);
  }

  if (spec.state) out.push('', `Shared state: initial ${cut(JSON.stringify(spec.state.initial), 300)} · persisted: ${(spec.state.persist || []).join(', ')}`);
  const d = spec.data || {};
  const fields = Object.entries(d.fields || {}).map(([k, f]) => `${k}:${f.type}${f.required ? '!' : ''}${f.enum ? `{${f.enum.length} values}` : ''}${f.min != null ? ` ≥${f.min}` : ''}${f.max != null ? ` ≤${f.max}` : ''}`);
  out.push('', `Data: ${d.module || 'js/data.js'} exports ${d.export || 'records'} (${d.count || '?'} records; seed ids ${(d.seed || []).map(r => r.id).join(', ')})` +
    `${Object.keys(d.extras || {}).length ? ` + extras ${Object.entries(d.extras).map(([k, v]) => `${k}(${Array.isArray(v) ? v.length : 'obj'})`).join(', ')}` : ''}`);
  out.push(`  fields: ${fields.join(', ')}`);
  if (d.seed?.length) out.push(`  sample ${d.export || 'records'}[0]: ${cut(JSON.stringify(d.seed[0], short), 500)}`);
  for (const [k, v] of Object.entries(d.extras || {})) out.push(`  sample ${k}${Array.isArray(v) ? '[0]' : ''}: ${cut(JSON.stringify(Array.isArray(v) ? v[0] : v, short), 400)}`);
  if (owner === 'data') {
    for (const [k, f] of Object.entries(d.fields || {})) if (f.enum) out.push(`  ${k} enum: ${cut(f.enum.join(' | '), 600)}`);
    if (d.rules?.length) out.push(`  rules: ${d.rules.join(' ; ')}`);
    if (d.note) out.push(`  note: ${cut(d.note, 900)}`);
    out.push('', 'Real samples (match their wording, lengths, number formats):');
    for (const p of sum?.pages?.length ? sum.pages : cap?.pages || []) for (const g of (p.cardGroups || []).slice(0, 2))
      out.push(`- ${p.name} ${g.itemSelector} ×${g.count}: ${(g.samples || []).slice(0, 3).map(s => JSON.stringify(cut(typeof s === 'string' ? s : s.text, 180))).join(' | ')}`);
    if (sum?.currency || sum?.pages?.[0]?.money) out.push(`money seen: ${JSON.stringify(sum.currency || sum.pages[0].money)}`);
  }

  if (owner !== 'data') {
    const tokensCss = path.join(dir, 'css', 'tokens.css');
    if (fs.existsSync(tokensCss)) out.push('', 'Tokens (css/tokens.css):', ...fs.readFileSync(tokensCss, 'utf-8').split('\n').filter(l => l.trim().startsWith('--')).map(l => '  ' + l.trim()));
    out.push('', 'Measured styles on your pages (target/summary.json):');
    const seen = new Set(); // pages sharing a layout print the same styles; show each once
    const once = line => { const key = line.replace(/^- \S+ /, ''); if (!seen.has(key)) seen.add(key), out.push(line); };
    for (const p of isShell ? [shellPage || pages[0]].filter(Boolean) : pages) {
      const dg = digestPage(sum, cap, p.source);
      if (!dg) { out.push(`- ${p.id}: no capture (source ${p.source ?? 'null'}) — design it in the measured visual language`); continue; }
      for (const [k, v] of Object.entries(dg.keyElements || {})) {
        if (isShell ? !['header', 'nav', 'footer', 'link', 'input', 'button', 'body'].includes(k) : ['header', 'nav', 'footer'].includes(k)) continue;
        once(`- ${p.id} ${k}: ${[...new Set([].concat(v).slice(0, 2).map(style))].join('  ||  ')}`);
      }
      if (!isShell) for (const g of (dg.cardGroups || []).slice(0, 2)) once(`- ${p.id} card ${g.itemSelector} ×${g.count}: ${style(g.itemStyle)}`);
      if (dg.headings?.length) out.push(`- ${p.id} headings: ${cut(dg.headings.slice(0, 12).join(' / '), 400)}`);
    }
    out.push('', API, '', await helperMarkup(dir));
  }

  const S = '<skill>';
  const C = `  node ${S}/scripts/check_replica.js --dir ${dir}`, T = `--target ${dir}/target   # then Read report/side-<page>-<vp>.png`;
  // Only commands that check something (the checker exits 2 on a selection that matches nothing); safe to paste as is.
  const cmds = owner === 'data' ? [`${C} --only data`] : [
    features.length && `${C} --owner ${owner} --only feature`,
    isShell ? shellPage && `${C} --only visual:${shellPage.id} ${T} (header/frame/footer only)`
      : pages.some(captured) && `${C} --owner ${owner} --only visual ${T}`].filter(Boolean);
  out.push('', 'Commands (the checker serves the replica itself; start no server):', ...(cmds.length ? cmds : ['  (none: nothing of yours has a check)']));
  return out.join('\n');
}

// realpath: import.meta.url has symlinks resolved but argv[1] doesn't (the skill is invoked through .claude/skills).
if (process.argv[1] && import.meta.url === pathToFileURL(fs.realpathSync(process.argv[1])).href) {
  const args = parseArgs();
  if (typeof args.dir !== 'string' || typeof args.owner !== 'string') {
    console.error('Usage: node scripts/brief.js --dir <replica> --owner <builder:name | builder:shell | data>');
    process.exit(2);
  }
  try {
    const skill = path.dirname(path.dirname(fs.realpathSync(process.argv[1])));
    console.log((await brief(path.resolve(args.dir), args.owner)).replaceAll('<skill>', skill));
  } catch (err) {
    console.error(err.message);
    process.exit(2);
  }
}
